sudo: false
language: python
python:
- 2.6
- 2.7
- 3.4
install:
- pip install -r requirements.txt
- pip install cython
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --upgrade; fi
- python setup.py build_ext --inplace
script:
- python -c "import bcolz; bcolz.test(heavy=True)"
notifications:
email: false
